global:
  external_labels:
    monitor: devops_monitor
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: node_exporter
    static_configs:
      - targets:
          - "node_exporter:9100"

  - job_name: kong
    static_configs:
      - targets:
          - "kong:8001"
